const products={
  'oud-royale':{name:'Oud Royale',category:'WOODY • INTENSE',price:'Rs. 3,500',size:'50ml',image:'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1000&q=85',description:'A rich, enveloping oud with a warm, unforgettable trail. Created for evenings that call for quiet confidence.',top:'Saffron',heart:'Rose & Amber',base:'Oud & Musk'},
  'golden-bloom':{name:'Golden Bloom',category:'FLORAL • RADIANT',price:'Rs. 3,200',size:'50ml',image:'https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1000&q=85',description:'Soft petals and luminous amber come together in a radiant composition with a graceful finish.',top:'Bergamot',heart:'Jasmine & Rose',base:'Amber & Musk'},
  'midnight-oud':{name:'Midnight Oud',category:'AMBER • MYSTERIOUS',price:'Rs. 3,800',size:'50ml',image:'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=85',description:'Deep amber, smoky woods and a touch of quiet confidence—made for the atmosphere after dark.',top:'Spices',heart:'Leather & Amber',base:'Oud & Sandalwood'}
};
const menu=document.querySelector('.menu-toggle');
if(menu){menu.addEventListener('click',()=>{const nav=document.querySelector('.site-nav');const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')})}
document.querySelectorAll('.year').forEach(el=>el.textContent=new Date().getFullYear());
const params=new URLSearchParams(window.location.search);const product=products[params.get('product')];
if(product&&document.querySelector('#product-name')){document.title=`${product.name} | Huzaifa Fragrance`;document.querySelector('#product-name').textContent=product.name;document.querySelector('#product-category').textContent=product.category;document.querySelector('#product-price').textContent=product.price;document.querySelector('#product-size').textContent=product.size;document.querySelector('#product-description').textContent=product.description;document.querySelector('#product-image').src=product.image;document.querySelector('#product-image').alt=`${product.name} perfume bottle`;document.querySelector('#top-notes').textContent=product.top;document.querySelector('#heart-notes').textContent=product.heart;document.querySelector('#base-notes').textContent=product.base;document.querySelector('#order-link').href=`https://wa.me/92XXXXXXXXXX?text=${encodeURIComponent(`Hello Huzaifa Fragrance, I would like to order ${product.name}.`)}`}
